# Generated by Django 3.0 on 2024-09-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=15)),
                ('FirstName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=15)),
            ],
        ),
    ]
